//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeatonaApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Actions_Log
    {
        public long Action_id { get; set; }
        public Nullable<int> Opration_id { get; set; }
        public Nullable<System.DateTime> Posting_DateTime { get; set; }
        public string description_status { get; set; }
        public string User_ID_Posting { get; set; }
        public Nullable<long> VisitID { get; set; }
        public string Note { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Oprations_sys Oprations_sys { get; set; }
    }
}
