//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeatonaApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyInfo
    {
        public int id { get; set; }
        public string Name { get; set; }
        public string NickName { get; set; }
        public string Logo { get; set; }
        public string BusinessDescription { get; set; }
        public string RateNumber { get; set; }
        public string Address { get; set; }
        public string NumberPhone1 { get; set; }
        public string NumberPhone2 { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public string Website { get; set; }
    }
}
