//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeatonaApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Oprations_sys
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Oprations_sys()
        {
            this.Actions_Log = new HashSet<Actions_Log>();
        }
    
        public int Opration_id { get; set; }
        public string OprationName { get; set; }
        public int Status { get; set; }
        public string OprationDescription { get; set; }
        public string ControllerName { get; set; }
        public string ClassName { get; set; }
        public string TableName { get; set; }
        public string RoleName { get; set; }
        public string ArabicOprationDescription { get; set; }
        public string IconClass { get; set; }
        public Nullable<int> ReferenceStatus { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Actions_Log> Actions_Log { get; set; }
    }
}
