//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeatonaApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Service
    {
        public long id { get; set; }
        public string ServiceNEN { get; set; }
        public string ServiceNAR { get; set; }
        public string Description { get; set; }
        public Nullable<long> ValueCoint { get; set; }
        public Nullable<long> CategoriesID { get; set; }
        public Nullable<long> ProviderID { get; set; }
    
        public virtual CategoriesService CategoriesService { get; set; }
        public virtual Provider Provider { get; set; }
    }
}
