//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeatonaApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WasteType
    {
        public long Id { get; set; }
        public string AName { get; set; }
        public string EName { get; set; }
        public string Color { get; set; }
        public string Image { get; set; }
        public int Status { get; set; }
        public string Evaluation { get; set; }
        public string Note { get; set; }
        public System.DateTime Posting_DateTime { get; set; }
        public Nullable<double> Cost { get; set; }
    }
}
